name: 'Create Terraform Workspce in Terraform Cloud/Terraform Enterprise'
description: 'Invoke Terraform API to create workspce in Terraform Cloud/Terraform Enterprise'
inputs:
  workSpaceName:
    description: 'Terraform workspace name'
    required: true
  organizationName:
    description: 'Terraform organization Name'
    required: true
  terraformToken:
    description: 'Terraform Token'
    required: true
outputs:
  workSpaceId: 
    description: 'Terraform WorkspaceId'
runs:
  using: 'node12'
  main: 'index.js'